name: Biên dịch kernel a14-6-1

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "Chọn KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Chọn nhánh ksu"
        required: true
        type: choice
        options:
          - Stable(Ổn định)
          - Dev(Phát triển)
          - Other(Khác/Đã chỉ định)
        default: Dev(Phát triển)
      version:
        description: 'Tên phiên bản tùy chỉnh (ví dụ: ký tự sau 6.1.93/để trống để sử dụng số phiên bản mặc định)'
        required: false
        type: string
jobs:

  build-kernel-a14-6-1:
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}

